// eslint-disable-next-line import/no-anonymous-default-export
export default [
  { label: "Accesorios para Vehículos", category: "MLM1747" },
  { label: "Agro", category: "MLM189530" },
  { label: "Alimentos y Bebidas", category: "MLM1403" },
  { label: "Animales y Mascotas", category: "MLM1071" },
  { label: "Antigüedades y Colecciones", category: "MLM1367" },
  { label: "Arte, Papelería y Mercería", category: "MLM1368" },
  { label: "Bebés", category: "MLM1384" },
  { label: "Belleza y Cuidado Personal", category: "MLM1246" },
  { label: "Celulares y Telefonía", category: "MLM1051" },
  { label: "Computación", category: "MLM1648" },
  { label: "Consolas y Videojuegos", category: "MLM1144" },
  { label: "Construcción", category: "MLM1500" },
  { label: "Cámaras y Accesorios", category: "MLM1039" },
  { label: "Deportes y Fitness", category: "MLM1276" },
  { label: "Electrodomésticos", category: "MLM1575" },
  { label: "Electrónica, Audio y Video", category: "MLM1000" },
  { label: "Herramientas", category: "MLM186863" },
  { label: "Hogar, Muebles y Jardín", category: "MLM1574" },
  { label: "Industrias y Oficinas", category: "MLM1499" },
  { label: "Instrumentos Musicales", category: "MLM1182" },
  { label: "Joyas y Relojes", category: "MLM3937" },
  { label: "Juegos y Juguetes", category: "MLM1132" },
  { label: "Libros, Revistas y Comics", category: "MLM3025" },
  { label: "Música, Películas y Series", category: "MLM1168" },
  { label: "Recuerdos, Cotillón y Fiestas", category: "MLM44011" },
  { label: "Ropa, Bolsas y Calzado", category: "MLM1430" },
  { label: "Salud y Equipamiento Médico", category: "MLM187772" },
  { label: "Otras Categorías", category: "MLM1953" }
]